services:
  postgres:
    container_name: postgres-db-sample
    build: ./db/image/
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres_db_sample
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass

volumes:
  db-data:
